# Generated by Django 4.0.3 on 2022-03-08 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.CharField(db_column='completed', max_length=20, verbose_name='成果完成人')),
                ('first', models.CharField(db_column='first', max_length=20, verbose_name='第一完成单位')),
                ('keyword', models.CharField(db_column='keyword', max_length=20, verbose_name='关键词')),
                ('introduction', models.CharField(db_column='induction', max_length=20, verbose_name='成果简介')),
                ('achievementype', models.CharField(db_column='actype', max_length=20, verbose_name='成果类别')),
                ('ydate', models.CharField(db_column='ydate', max_length=20, verbose_name='研究起止时间')),
            ],
            options={
                'db_table': 'achievement',
            },
        ),
    ]
