# Generated by Django 4.0.3 on 2022-03-08 09:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achievement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='patent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patentname', models.CharField(db_column='patename', max_length=20, verbose_name='专利名')),
                ('patenttype', models.CharField(db_column='patenttype', max_length=20, verbose_name='专利类型')),
                ('applicant', models.CharField(db_column='applicant', max_length=20, verbose_name='申请人')),
                ('address', models.CharField(db_column='address', max_length=20, verbose_name='地址')),
                ('inventor', models.CharField(db_column='inventor', max_length=20, verbose_name='发明人')),
                ('special', models.CharField(db_column='special', max_length=20, verbose_name='专题')),
                ('album', models.CharField(db_column='album', max_length=20, verbose_name='专辑')),
                ('pages', models.IntegerField(db_column='pages', verbose_name='页数')),
                ('agency', models.CharField(db_column='agency', max_length=20, verbose_name='代理机构')),
                ('fdate', models.DateTimeField(db_column='fdate', default=datetime.datetime(2022, 3, 8, 17, 6, 9, 264799), verbose_name='申请日')),
                ('abstract', models.CharField(db_column='abstract', max_length=20, verbose_name='摘要')),
            ],
            options={
                'db_table': 'patent',
            },
        ),
    ]
