# Generated by Django 4.0.3 on 2022-03-08 09:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achievement', '0002_patent'),
    ]

    operations = [
        migrations.CreateModel(
            name='paper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('papername', models.CharField(db_column='papername', max_length=20, verbose_name='标题')),
                ('author', models.CharField(db_column='author', max_length=20, verbose_name='作者')),
                ('school', models.CharField(db_column='school', max_length=20, verbose_name='学校')),
                ('abstract', models.CharField(db_column='abstract', max_length=20, verbose_name='摘要')),
                ('keyword', models.CharField(db_column='keyword', max_length=20, verbose_name='关键词')),
                ('tteacher', models.CharField(db_column='tteacher', max_length=20, verbose_name='导师')),
                ('major', models.CharField(db_column='major', max_length=20, verbose_name='学科专业')),
                ('content', models.FileField(db_column='content', upload_to='research/论文/%Y/', verbose_name='详情')),
            ],
            options={
                'db_table': 'paper',
            },
        ),
        migrations.AlterField(
            model_name='patent',
            name='fdate',
            field=models.DateTimeField(db_column='fdate', default=datetime.datetime(2022, 3, 8, 17, 6, 19, 902706), verbose_name='申请日'),
        ),
    ]
