# Generated by Django 4.0.3 on 2022-03-08 09:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achievement', '0003_paper_alter_patent_fdate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Academicjournals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('journalsname', models.CharField(db_column='joname', max_length=20, verbose_name='标题')),
                ('author', models.CharField(db_column='author', max_length=20, verbose_name='作者')),
                ('mechanism', models.CharField(db_column='mechanism', max_length=20, verbose_name='机构')),
                ('abstract', models.CharField(db_column='abstract', max_length=20, verbose_name='摘要')),
                ('keyword', models.CharField(db_column='keyword', max_length=20, verbose_name='关键词')),
                ('special', models.CharField(db_column='special', max_length=20, verbose_name='专题')),
                ('album', models.CharField(db_column='album', max_length=20, verbose_name='专辑')),
                ('Classificationnumber', models.CharField(db_column='clnumber', max_length=20, verbose_name='分类号')),
                ('content', models.FileField(db_column='content', upload_to='research/期刊/%Y/', verbose_name='详情')),
            ],
            options={
                'db_table': 'acjournals',
            },
        ),
        migrations.AlterField(
            model_name='patent',
            name='fdate',
            field=models.DateTimeField(db_column='fdate', default=datetime.datetime(2022, 3, 8, 17, 6, 31, 396133), verbose_name='申请日'),
        ),
    ]
