# Generated by Django 4.0.1 on 2022-03-10 14:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achievement', '0008_alter_patent_fdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicjournals',
            name='content',
            field=models.CharField(db_column='content', max_length=50, verbose_name='详情'),
        ),
        migrations.AlterField(
            model_name='paper',
            name='content',
            field=models.CharField(db_column='content', max_length=50, verbose_name='详情'),
        ),
        migrations.AlterField(
            model_name='patent',
            name='fdate',
            field=models.DateTimeField(db_column='fdate', default=datetime.datetime(2022, 3, 10, 22, 38, 45, 948762), verbose_name='申请日'),
        ),
    ]
