# Generated by Django 4.0.1 on 2022-03-16 13:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achievement', '0009_alter_academicjournals_content_alter_paper_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patent',
            name='fdate',
            field=models.DateTimeField(db_column='fdate', default=datetime.datetime(2022, 3, 16, 21, 19, 56, 562622), verbose_name='申请日'),
        ),
    ]
