# Generated by Django 4.0.1 on 2022-03-22 11:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achievement', '0010_alter_patent_fdate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='academicjournals',
            name='Classificationnumber',
        ),
        migrations.RemoveField(
            model_name='academicjournals',
            name='album',
        ),
        migrations.RemoveField(
            model_name='academicjournals',
            name='special',
        ),
        migrations.AlterField(
            model_name='patent',
            name='fdate',
            field=models.DateTimeField(db_column='fdate', default=datetime.datetime(2022, 3, 22, 19, 38, 23, 501988), verbose_name='申请日'),
        ),
    ]
