# Generated by Django 4.0.1 on 2022-03-22 13:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achievement', '0012_alter_academicjournals_abstract_alter_patent_fdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicjournals',
            name='abstract',
            field=models.TextField(db_column='abstract', verbose_name='摘要'),
        ),
        migrations.AlterField(
            model_name='patent',
            name='fdate',
            field=models.DateTimeField(db_column='fdate', default=datetime.datetime(2022, 3, 22, 21, 2, 35, 825235), verbose_name='申请日'),
        ),
    ]
