# Generated by Django 4.0.1 on 2022-03-22 13:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achievement', '0013_alter_academicjournals_abstract_alter_patent_fdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicjournals',
            name='content',
            field=models.TextField(db_column='content', verbose_name='详情'),
        ),
        migrations.AlterField(
            model_name='patent',
            name='fdate',
            field=models.DateTimeField(db_column='fdate', default=datetime.datetime(2022, 3, 22, 21, 3, 42, 134825), verbose_name='申请日'),
        ),
    ]
