# Generated by Django 4.0.1 on 2022-03-22 13:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achievement', '0014_alter_academicjournals_content_alter_patent_fdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='abstract',
            field=models.TextField(db_column='abstract', verbose_name='摘要'),
        ),
        migrations.AlterField(
            model_name='paper',
            name='content',
            field=models.TextField(db_column='content', verbose_name='详情'),
        ),
        migrations.AlterField(
            model_name='patent',
            name='fdate',
            field=models.DateTimeField(db_column='fdate', default=datetime.datetime(2022, 3, 22, 21, 4, 33, 956980), verbose_name='申请日'),
        ),
    ]
