# Generated by Django 4.0.1 on 2022-03-22 13:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achievement', '0015_alter_paper_abstract_alter_paper_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicjournals',
            name='journalsname',
            field=models.CharField(db_column='joname', max_length=50, verbose_name='标题'),
        ),
        migrations.AlterField(
            model_name='patent',
            name='fdate',
            field=models.DateTimeField(db_column='fdate', default=datetime.datetime(2022, 3, 22, 21, 54, 21, 696978), verbose_name='申请日'),
        ),
    ]
