# Generated by Django 4.0.1 on 2022-03-23 06:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achievement', '0017_alter_academicjournals_keyword_alter_patent_fdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='papername',
            field=models.TextField(db_column='papername', verbose_name='标题'),
        ),
        migrations.AlterField(
            model_name='patent',
            name='fdate',
            field=models.DateTimeField(db_column='fdate', default=datetime.datetime(2022, 3, 23, 14, 55, 4, 899951), verbose_name='申请日'),
        ),
    ]
