# Generated by Django 4.0.1 on 2022-03-23 06:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achievement', '0019_alter_paper_keyword_alter_paper_major_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='keyword',
            field=models.TextField(db_column='keyword', verbose_name='关键词'),
        ),
        migrations.AlterField(
            model_name='patent',
            name='fdate',
            field=models.DateTimeField(db_column='fdate', default=datetime.datetime(2022, 3, 23, 14, 57, 58, 622044), verbose_name='申请日'),
        ),
    ]
