# Generated by Django 4.0.1 on 2022-03-23 08:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achievement', '0020_alter_paper_keyword_alter_patent_fdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patent',
            name='abstract',
            field=models.TextField(db_column='abstract', verbose_name='摘要'),
        ),
        migrations.AlterField(
            model_name='patent',
            name='address',
            field=models.TextField(db_column='address', verbose_name='地址'),
        ),
        migrations.AlterField(
            model_name='patent',
            name='agency',
            field=models.TextField(db_column='agency', verbose_name='代理机构'),
        ),
        migrations.AlterField(
            model_name='patent',
            name='album',
            field=models.CharField(db_column='album', max_length=50, verbose_name='专辑'),
        ),
        migrations.AlterField(
            model_name='patent',
            name='applicant',
            field=models.CharField(db_column='applicant', max_length=50, verbose_name='申请人'),
        ),
        migrations.AlterField(
            model_name='patent',
            name='fdate',
            field=models.DateTimeField(db_column='fdate', default=datetime.datetime(2022, 3, 23, 16, 5, 43, 39673), verbose_name='申请日'),
        ),
        migrations.AlterField(
            model_name='patent',
            name='inventor',
            field=models.CharField(db_column='inventor', max_length=50, verbose_name='发明人'),
        ),
        migrations.AlterField(
            model_name='patent',
            name='patenttype',
            field=models.CharField(db_column='patenttype', max_length=50, verbose_name='专利类型'),
        ),
    ]
