# Generated by Django 4.0.1 on 2022-03-23 08:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achievement', '0021_alter_patent_abstract_alter_patent_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievement',
            name='title',
            field=models.TextField(db_column='title', default='', verbose_name='标题'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='achievement',
            name='achievementype',
            field=models.CharField(db_column='actype', max_length=30, verbose_name='成果类别'),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='completed',
            field=models.TextField(db_column='completed', verbose_name='成果完成人'),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='first',
            field=models.CharField(db_column='first', max_length=40, verbose_name='第一完成单位'),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='introduction',
            field=models.TextField(db_column='induction', verbose_name='成果简介'),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='keyword',
            field=models.TextField(db_column='keyword', verbose_name='关键词'),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='ydate',
            field=models.TextField(db_column='ydate', verbose_name='研究起止时间'),
        ),
        migrations.AlterField(
            model_name='patent',
            name='fdate',
            field=models.DateTimeField(db_column='fdate', default=datetime.datetime(2022, 3, 23, 16, 48, 54, 826024), verbose_name='申请日'),
        ),
    ]
