# Generated by Django 4.0.1 on 2022-04-05 11:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achievement', '0022_achievement_title_alter_achievement_achievementype_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patent',
            name='fdate',
            field=models.DateTimeField(db_column='fdate', default=datetime.datetime(2022, 4, 5, 19, 1, 52, 220433), verbose_name='申请日'),
        ),
    ]
