# Generated by Django 4.0.1 on 2022-04-27 13:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achievement', '0046_alter_patent_fdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='academicjournals',
            name='unit',
            field=models.CharField(db_column='unit', default=None, max_length=50, verbose_name='所属学院'),
        ),
        migrations.AddField(
            model_name='academicmonograph',
            name='unit',
            field=models.CharField(db_column='unit', default=None, max_length=50, verbose_name='所属学院'),
        ),
        migrations.AddField(
            model_name='achievement',
            name='unit',
            field=models.CharField(db_column='unit', default=None, max_length=50, verbose_name='所属学院'),
        ),
        migrations.AddField(
            model_name='paper',
            name='unit',
            field=models.CharField(db_column='unit', default=None, max_length=50, verbose_name='所属学院'),
        ),
        migrations.AddField(
            model_name='patent',
            name='unit',
            field=models.CharField(db_column='unit', default=None, max_length=50, verbose_name='所属学院'),
        ),
        migrations.AlterField(
            model_name='patent',
            name='fdate',
            field=models.DateTimeField(db_column='fdate', default=datetime.datetime(2022, 4, 27, 21, 52, 31, 91489), verbose_name='申请日'),
        ),
    ]
