# Generated by Django 4.0.1 on 2022-05-02 01:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achievement', '0047_academicjournals_unit_academicmonograph_unit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patent',
            name='fdate',
            field=models.DateTimeField(db_column='fdate', default=datetime.datetime(2022, 5, 2, 9, 1, 30, 862990), verbose_name='申请日'),
        ),
    ]
