# Generated by Django 4.0.1 on 2022-05-03 08:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achievement', '0048_alter_patent_fdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='academicjournals',
            name='fdate',
            field=models.DateTimeField(db_column='fdate', default=datetime.datetime(2022, 5, 3, 16, 44, 59, 844219), verbose_name='发表日期'),
        ),
        migrations.AddField(
            model_name='paper',
            name='fdate',
            field=models.DateTimeField(db_column='fdate', default=datetime.datetime(2022, 5, 3, 16, 44, 59, 845220), verbose_name='发表日期'),
        ),
        migrations.AlterField(
            model_name='patent',
            name='fdate',
            field=models.DateTimeField(db_column='fdate', default=datetime.datetime(2022, 5, 3, 16, 44, 59, 845220), verbose_name='申请日'),
        ),
    ]
