# Generated by Django 4.0.1 on 2022-05-03 09:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achievement', '0049_academicjournals_fdate_paper_fdate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicjournals',
            name='fdate',
            field=models.DateTimeField(db_column='fdate', default=datetime.datetime(2022, 5, 3, 17, 50, 15, 625663), verbose_name='发表日期'),
        ),
        migrations.AlterField(
            model_name='paper',
            name='fdate',
            field=models.CharField(db_column='fdate', default='', max_length=30, verbose_name='发表日期'),
        ),
        migrations.AlterField(
            model_name='patent',
            name='fdate',
            field=models.DateTimeField(db_column='fdate', default=datetime.datetime(2022, 5, 3, 17, 50, 15, 627664), verbose_name='申请日'),
        ),
    ]
