# Generated by Django 4.0.1 on 2022-05-14 09:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achievement', '0050_alter_academicjournals_fdate_alter_paper_fdate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicjournals',
            name='fdate',
            field=models.DateTimeField(db_column='fdate', default=datetime.datetime(2022, 5, 14, 9, 43, 57, 307132), verbose_name='发表日期'),
        ),
        migrations.AlterField(
            model_name='paper',
            name='author',
            field=models.CharField(db_column='author', max_length=60, verbose_name='作者'),
        ),
        migrations.AlterField(
            model_name='paper',
            name='school',
            field=models.CharField(db_column='school', max_length=60, verbose_name='学校'),
        ),
        migrations.AlterField(
            model_name='paper',
            name='tteacher',
            field=models.CharField(db_column='tteacher', max_length=60, verbose_name='导师'),
        ),
        migrations.AlterField(
            model_name='patent',
            name='fdate',
            field=models.DateTimeField(db_column='fdate', default=datetime.datetime(2022, 5, 14, 9, 43, 57, 308132), verbose_name='申请日'),
        ),
    ]
