# Generated by Django 4.0.1 on 2022-05-21 10:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achievement', '0051_alter_academicjournals_fdate_alter_paper_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicjournals',
            name='fdate',
            field=models.DateTimeField(db_column='fdate', default=datetime.datetime(2022, 5, 21, 10, 54, 56, 698451), verbose_name='发表日期'),
        ),
        migrations.AlterField(
            model_name='patent',
            name='fdate',
            field=models.DateTimeField(db_column='fdate', default=datetime.datetime(2022, 5, 21, 10, 54, 56, 699456), verbose_name='申请日'),
        ),
    ]
