# Generated by Django 4.0.1 on 2022-05-21 13:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achievement', '0056_alter_academicjournals_fdate_alter_patent_fdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicjournals',
            name='fdate',
            field=models.DateTimeField(db_column='fdate', default=datetime.datetime(2022, 5, 21, 13, 42, 22, 5391), verbose_name='发表日期'),
        ),
        migrations.AlterField(
            model_name='patent',
            name='fdate',
            field=models.DateTimeField(db_column='fdate', default=datetime.datetime(2022, 5, 21, 13, 42, 22, 6389), verbose_name='申请日'),
        ),
    ]
