# Generated by Django 4.0.1 on 2022-03-16 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
        ('entryaward', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievementaward',
            name='upuser',
            field=models.ForeignKey(db_column='upuser', on_delete=django.db.models.deletion.CASCADE, to='customer.user', verbose_name='上传用户'),
        ),
        migrations.AlterField(
            model_name='achievementaward',
            name='winner',
            field=models.CharField(db_column='winner', max_length=40, verbose_name='得奖人'),
        ),
        migrations.AlterField(
            model_name='entryawards',
            name='upuser',
            field=models.ForeignKey(db_column='upuser', on_delete=django.db.models.deletion.CASCADE, to='customer.user', verbose_name='上传用户'),
        ),
        migrations.AlterField(
            model_name='entryawards',
            name='winner',
            field=models.CharField(db_column='winner', max_length=40, verbose_name='得奖人'),
        ),
    ]
