# Generated by Django 4.0.1 on 2022-04-08 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entryaward', '0002_alter_achievementaward_upuser_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievementaward',
            name='unit',
            field=models.CharField(db_column='unit', default='山东女子学院', max_length=30, verbose_name='单位'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='entryawards',
            name='unit',
            field=models.CharField(db_column='unit', default='山东女子学院', max_length=30, verbose_name='单位'),
            preserve_default=False,
        ),
    ]
