# Generated by Django 4.0.3 on 2022-03-08 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('jobno', models.IntegerField(db_column='jobno', primary_key=True, serialize=False, verbose_name='工号')),
                ('name', models.CharField(db_column='name', max_length=20, verbose_name='姓名')),
                ('pwd', models.CharField(db_column='pwd', max_length=30, verbose_name='密码')),
                ('teatype', models.IntegerField(db_column='teatype', default=0, verbose_name='类别')),
                ('unit', models.CharField(db_column='unit', max_length=25, verbose_name='单位名称')),
            ],
            options={
                'db_table': 'User',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='name', max_length=20, verbose_name='姓名')),
                ('sex', models.CharField(db_column='sex', default='男', max_length=4, verbose_name='性别')),
                ('brith', models.CharField(db_column='brith', max_length=15, verbose_name='出生日期')),
                ('mail', models.EmailField(db_column='mail', max_length=20, verbose_name='邮箱')),
                ('phone', models.CharField(db_column='phone', max_length=12, verbose_name='联系方式')),
                ('access', models.CharField(db_column='access', max_length=20, verbose_name='地址')),
                ('position', models.CharField(db_column='position', max_length=15, verbose_name='职位')),
                ('education', models.CharField(db_column='education', max_length=10, verbose_name='学历')),
                ('proid', models.ForeignKey(db_column='proid', on_delete=django.db.models.deletion.CASCADE, to='customer.user', verbose_name='用户id')),
            ],
            options={
                'db_table': 'Profile',
            },
        ),
    ]
