# Generated by Django 4.0.1 on 2022-04-08 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_alter_profile_table_alter_user_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='proid',
        ),
    ]
