# Generated by Django 4.0.1 on 2022-04-24 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_remove_profile_proid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='access',
            field=models.CharField(db_column='access', max_length=50, verbose_name='地址'),
        ),
    ]
