# Generated by Django 4.0.1 on 2022-05-02 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_alter_profile_access'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='unit',
            field=models.CharField(db_column='unit', default='', max_length=40, verbose_name='单位名称'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='unit',
            field=models.CharField(db_column='unit', max_length=40, verbose_name='单位名称'),
        ),
    ]
