# Generated by Django 4.0.1 on 2022-05-14 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_profile_unit_alter_user_unit'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name_plural': '用户管理'},
        ),
    ]
