# Generated by Django 4.0.1 on 2022-04-06 06:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('research', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Objects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectname', models.CharField(db_column='projectname', max_length=20, verbose_name='项目名称')),
                ('projecttype', models.CharField(db_column='projecttype', max_length=20, verbose_name='项目分类')),
                ('projectmember', models.CharField(db_column='projectmember', max_length=20, verbose_name='项目成员')),
                ('pverify', models.IntegerField(db_column='pverify', default=-1, verbose_name='项目状态')),
                ('ydate', models.CharField(db_column='ydate', max_length=20, verbose_name='起止时间')),
                ('verify', models.IntegerField(db_column='verify', default=-1, verbose_name='审核状态')),
            ],
            options={
                'db_table': 'objects',
            },
        ),
        migrations.CreateModel(
            name='Fund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contractamount', models.DecimalField(db_column='comount', decimal_places=2, max_digits=8, verbose_name='合同金额')),
                ('arrivalamount', models.DecimalField(db_column='arrmount', decimal_places=2, max_digits=8, verbose_name='到账金额')),
                ('outamount', models.DecimalField(db_column='outamount', decimal_places=2, max_digits=8, verbose_name='支出金额')),
                ('outsideamount', models.DecimalField(db_column='outmount', decimal_places=2, max_digits=8, verbose_name='外拨金额')),
                ('amount', models.DecimalField(db_column='amount', decimal_places=2, max_digits=8, verbose_name='经费明细')),
                ('projectid', models.ForeignKey(db_column='projectid', on_delete=django.db.models.deletion.CASCADE, to='research.objects', verbose_name='项目名称')),
            ],
            options={
                'db_table': 'fund',
            },
        ),
        migrations.CreateModel(
            name='Dynamic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress', models.CharField(db_column='progress', max_length=20, verbose_name='项目进度')),
                ('performance', models.CharField(db_column='performance', max_length=20, verbose_name='完成进度')),
                ('ddate', models.CharField(db_column='ddate', max_length=20, verbose_name='当前时间')),
                ('projectid', models.ForeignKey(db_column='projectid', on_delete=django.db.models.deletion.CASCADE, to='research.objects', verbose_name='项目名称')),
            ],
            options={
                'db_table': 'dynamic',
            },
        ),
    ]
