# Generated by Django 4.0.1 on 2022-04-06 07:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0002_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Objects',
            new_name='Project',
        ),
        migrations.RemoveField(
            model_name='dynamic',
            name='projectid',
        ),
        migrations.RemoveField(
            model_name='fund',
            name='projectid',
        ),
        migrations.AddField(
            model_name='dynamic',
            name='project',
            field=models.ForeignKey(db_column='project', default=1, on_delete=django.db.models.deletion.CASCADE, to='research.project', verbose_name='项目名称'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fund',
            name='project',
            field=models.ForeignKey(db_column='project', default=1, on_delete=django.db.models.deletion.CASCADE, to='research.project', verbose_name='项目名称'),
            preserve_default=False,
        ),
    ]
