# Generated by Django 4.0.1 on 2022-04-06 07:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0003_rename_objects_project_remove_dynamic_projectid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fund',
            name='project',
        ),
        migrations.AddField(
            model_name='project',
            name='fund',
            field=models.ForeignKey(db_column='fund', default=1, on_delete=django.db.models.deletion.CASCADE, to='research.fund', verbose_name='经费'),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='project',
            table='projects',
        ),
    ]
