# Generated by Django 4.0.1 on 2022-04-06 07:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0004_remove_fund_project_project_fund_alter_project_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='fund',
        ),
        migrations.AddField(
            model_name='fund',
            name='project',
            field=models.ForeignKey(db_column='project', default=1, on_delete=django.db.models.deletion.CASCADE, to='research.project', verbose_name='项目名称'),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='project',
            table='objects',
        ),
    ]
