# Generated by Django 4.0.1 on 2022-04-06 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0005_remove_project_fund_fund_project_alter_project_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='project',
            table='project',
        ),
    ]
