# Generated by Django 4.0.1 on 2022-04-06 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0007_alter_fund_project_alter_project_pverify'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fund',
            name='amount',
            field=models.TextField(db_column='amount', verbose_name='经费明细'),
        ),
    ]
