# Generated by Django 4.0.3 on 2022-03-08 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_column='title', max_length=20, verbose_name='标题')),
                ('releasedate', models.CharField(db_column='release', max_length=20, verbose_name='发布时间')),
                ('content', models.CharField(db_column='content', max_length=20, verbose_name='内容')),
                ('type', models.CharField(db_column='type', max_length=20, verbose_name='类型')),
                ('releaser', models.ForeignKey(db_column='releaser', on_delete=django.db.models.deletion.CASCADE, to='customer.user', verbose_name='发布人')),
            ],
            options={
                'db_table': 'anment',
            },
        ),
        migrations.CreateModel(
            name='academicexchange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exchangename', models.CharField(db_column='exname', max_length=20, verbose_name='会议名称')),
                ('organizer', models.CharField(db_column='organizer', max_length=20, verbose_name='主办单位')),
                ('type', models.CharField(db_column='type', max_length=20, verbose_name='会议类型')),
                ('cdate', models.CharField(db_column='cdate', max_length=20, verbose_name='参会日期')),
                ('verify', models.IntegerField(db_column='verify', default=-1, verbose_name='审核状态')),
                ('attendee', models.ManyToManyField(db_column='attendee', to='customer.user', verbose_name='参会人')),
            ],
            options={
                'db_table': 'acexchange',
            },
        ),
    ]
