# Generated by Django 4.0.1 on 2022-04-06 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_alter_profile_table_alter_user_table'),
        ('bulletin', '0003_rename_exchangename_academicexchange_exname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicexchange',
            name='attendee',
            field=models.ManyToManyField(to='customer.User'),
        ),
    ]
